//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HighSpeedTollSystemEntities : DbContext
    {
        public HighSpeedTollSystemEntities()
            : base("name=HighSpeedTollSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Action> TB_Action { get; set; }
        public virtual DbSet<TB_AuditStatus> TB_AuditStatus { get; set; }
        public virtual DbSet<TB_Balance> TB_Balance { get; set; }
        public virtual DbSet<TB_CarAudit> TB_CarAudit { get; set; }
        public virtual DbSet<TB_carID> TB_carID { get; set; }
        public virtual DbSet<TB_FeedBack> TB_FeedBack { get; set; }
        public virtual DbSet<TB_HighSpeedState> TB_HighSpeedState { get; set; }
        public virtual DbSet<TB_MTC> TB_MTC { get; set; }
        public virtual DbSet<TB_OverSite> TB_OverSite { get; set; }
        public virtual DbSet<TB_OwnershipArea> TB_OwnershipArea { get; set; }
        public virtual DbSet<TB_pcUser> TB_pcUser { get; set; }
        public virtual DbSet<TB_StationManager> TB_StationManager { get; set; }
        public virtual DbSet<TB_Tollgate> TB_Tollgate { get; set; }
        public virtual DbSet<TB_user> TB_user { get; set; }
        public virtual DbSet<TB_UserAudit> TB_UserAudit { get; set; }
        public virtual DbSet<TB_UserInfo> TB_UserInfo { get; set; }
        public virtual DbSet<View_Action> View_Action { get; set; }
        public virtual DbSet<View_Car> View_Car { get; set; }
        public virtual DbSet<View_CarInfo> View_CarInfo { get; set; }
        public virtual DbSet<View_StationDetail> View_StationDetail { get; set; }
        public virtual DbSet<View_TollStation> View_TollStation { get; set; }
        public virtual DbSet<View_UserFeedBackAudit> View_UserFeedBackAudit { get; set; }
        public virtual DbSet<View_UserInfo> View_UserInfo { get; set; }
    }
}
