//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CarAudit
    {
        public int id { get; set; }
        public string 车牌号 { get; set; }
        public int 用户编号 { get; set; }
        public int 状态编号 { get; set; }
        public string 车牌照片前 { get; set; }
        public string 车牌照片后 { get; set; }
        public int 信息编号 { get; set; }
    }
}
