//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OverSite
    {
        public int id { get; set; }
        public int 进站编号 { get; set; }
        public int 站点编号 { get; set; }
        public string 过站时间 { get; set; }
    }
}
