//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_StationManager
    {
        public int 管理员编号 { get; set; }
        public string 身份证号码 { get; set; }
        public string 姓名 { get; set; }
        public string 密码 { get; set; }
        public string 管区id { get; set; }
    }
}
