//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Action
    {
        public string 操作动作 { get; set; }
        public int id { get; set; }
        public int 操作id { get; set; }
        public int 操作金额 { get; set; }
        public int 用户编号 { get; set; }
        public string 时间 { get; set; }
        public int 当时余额 { get; set; }
    }
}
